// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdkUyIKnu4fwZG6lg5GmMvASE4Whtn4mI',
    appId: '1:865012510269:web:a4a259c8803e330395c454',
    messagingSenderId: '865012510269',
    projectId: 'pharmacy-bc18d',
    authDomain: 'pharmacy-bc18d.firebaseapp.com',
    storageBucket: 'pharmacy-bc18d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAduJEqk0_OzMyjI2M_ed-OoRFE1y9el6Y',
    appId: '1:865012510269:android:3f09a552780c2e9195c454',
    messagingSenderId: '865012510269',
    projectId: 'pharmacy-bc18d',
    storageBucket: 'pharmacy-bc18d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6vSm8FZOFh_WAYtq0aTmdefk-Od0jfRQ',
    appId: '1:865012510269:ios:d83deb0719070b4d95c454',
    messagingSenderId: '865012510269',
    projectId: 'pharmacy-bc18d',
    storageBucket: 'pharmacy-bc18d.appspot.com',
    iosClientId: '865012510269-ou5ar18d1ppst3tdd2tvqmjtu6p0gkn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6vSm8FZOFh_WAYtq0aTmdefk-Od0jfRQ',
    appId: '1:865012510269:ios:d4010357e114fb1d95c454',
    messagingSenderId: '865012510269',
    projectId: 'pharmacy-bc18d',
    storageBucket: 'pharmacy-bc18d.appspot.com',
    iosClientId: '865012510269-477122u20801kr6ck1sc4v32i6rql2bp.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacy.RunnerTests',
  );
}
